Clean code
Star-Academy/Summer1400-SE-Team22 pull request #1
Opened 2021-07-28 07:22 UTC by abolfazlghalandary

2021-08-03 08:22 UTC, navidnt commented on src/main/java/Searcher.java
> +public class Searcher {
این کلاس خیلی بزرگه. فکر کنم می شد به چند تا کلاس تقسیمش کرد

2021-08-07 06:58 UTC, Morovati306 commented on src/main/java/Searcher.java
> +public class Searcher {
کلاس حدود ۱۲۰ خط هست که حدود ۵۰  خط اون هم اسپیس  و براکت هست که برای تمیزی استفاده شده.
تنها کاری که انجام میگیرد سرچ کردن و پیدا کردن جواب هاست.
کلاس از ۹ تابع کوچک تشکیل شده که هر کدام وظیفه مشخصی دارند.
و کار های منحصر به فردی رو جدا انجام میدهند از نظر کلین کد بودن مشکل خاصی ندارد.
اندازه کلاس با ماکسیمم اندازه یک کلاس فاصله دارد.
از نظرت ممنونم

2021-08-10 12:55 UTC, navidnt reviewed
a

2021-08-11 11:52 UTC, MahdiHma requested changes
در کل کد مناسبی بود. بجز کلاس 
searcher

ترجیحا gitignore 
را قرار دهید به گونه‌ای که فایل‌های اضافی مانند فایل‌های مربوط به دیتا و فایل‌های xml
حذف بشوند

2021-08-11 11:52 UTC, MahdiHma commented on pom.xml
> +</project>
به کمک
https://www.toptal.com/developers/gitignore
فایل‌های اضافی را گیت ایگنور کنید.

2021-08-11 11:52 UTC, MahdiHma commented on src/main/java/FileReader.java
> +}
می‌توانید بجای return
یک اکسپشن شخصی سازی شده استفاده کنید و آن را 
throw 
کنید به گونه‌ای که پیامش قابل فهم باشه

2021-08-11 11:52 UTC, MahdiHma commented on src/main/java/Searcher.java
> +public class Searcher {
قاعده 
single responsibility
برای این کد رعایت نشده.
این کلاس می‌تونه به حداقل دو زیر کلاس تقسیم بشه که کار‌های مختلفی انجام میدن.

2021-08-14 20:32 UTC, Morovati306 commented on src/main/java/Searcher.java
> +public class Searcher {
<p dir = "rtl">
با توجه به تنیدگی و ارتباط شدید محتوا
از شیوه اکسترکت متدز برای خوانا تر کردن استفاده کردیم.
</p>

2021-08-14 20:34 UTC, Morovati306 commented on pom.xml
> +</project>
انجام شد

2021-08-15 05:55 UTC, Morovati306 commented on src/main/java/Searcher.java
> +public class Searcher {
<p dir = "rtl">
این کلاس از دو زیر کلاس تشکیل شده است
<br>
یک متد و چندین فیلد را حذف کردیم و از کلاس 
SearchingExpretion
<br>
بهتر استفاده شد.
</p>

2021-08-16 13:35 UTC, AlirezaT99 approved these changes
کامنت‌هام در مورد
[این پی‌آر](https://github.com/Star-Academy/Summer1400-SE-Team22/pull/2)
اینجا هم برقرارند.
خسته نباشید.

2021-08-16 17:19 UTC, MahdiHma approved these changes
خیلی عالی
خدا قوت و خسته نباشید.

2021-08-17 06:48 UTC, merged