Unit test
Star-Academy/Summer1400-SE-Team22 pull request #2
Opened 2021-07-28 11:46 UTC by Morovati306

2021-08-03 08:15 UTC, pourya-momtaz approved these changes
everything seems to be ok

2021-08-10 12:53 UTC, navidnt reviewed
a

2021-08-10 19:21 UTC, AlirezaT99 commented
<div dir="rtl">
اون closes در توضیحات بالا چیزی رو نمی‌بنده
</div>

2021-08-10 19:34 UTC, AlirezaT99 commented on src/main/java/InvertedIndex.java
> +    }
<div dir="rtl">
حتما این رشته‌ها رو بصورت const String ذخیره کنید.
</div>

2021-08-10 19:34 UTC, AlirezaT99 commented on src/main/java/InvertedIndex.java
> +            List<WordInfo> idx = index.computeIfAbsent(word, k -> new LinkedList<>());
<div dir="rtl">
کمی بالاتر برای اسکوپ یک خطی آکولاد گذاشته بودید.
یا کلا بگذارید یا کلا نگذارید (اما ترجیحا همیشه بگذارید)
</div>

2021-08-10 19:34 UTC, AlirezaT99 commented on src/main/java/Main.java
> +    }
<div dir="rtl">
مجددا رشته تبدیل به const جدا شه.
</div>

2021-08-10 19:34 UTC, AlirezaT99 commented on src/main/java/Searcher.java
> +            return null;
<div dir="rtl">
سعی کنید هیچوقت null برنگردونید
</div>

2021-08-10 19:34 UTC, AlirezaT99 commented on src/main/java/Searcher.java
> +
<div dir="rtl">
درستش existsـه فکر می‌کنم
</div>

2021-08-11 12:04 UTC, MahdiHma requested changes
<div dir='rtl'>
خدا قوت. کد خوب و تمیزی بود. نیاز به تغییر searcher وجود دارد.
همچنین علیکم به گیت ایگنور

خدا قوت و خسته نباشد
</div>

2021-08-11 12:04 UTC, MahdiHma commented on src/main/java/InvertedIndex.java
> +    }
:+1:

2021-08-11 12:04 UTC, MahdiHma commented on src/main/java/InvertedIndex.java
> +            List<WordInfo> idx = index.computeIfAbsent(word, k -> new LinkedList<>());
:+1:

2021-08-11 12:04 UTC, MahdiHma commented on src/main/java/Searcher.java
> +}
در پول ریکوئست کلین کد هم اشاره کردم که این کلاس می‌تواند به حداقل دو زیرکلاس تقسیم شود.

2021-08-14 16:44 UTC, AlirezaT99 approved these changes
خسته نباشید :)

2021-08-14 20:29 UTC, Morovati306 commented on src/main/java/Searcher.java
> +}
<p dir = "rtl">
ممنون
این کلاس از اون جایی که تست های آن نوشته شده بود 
امکان تغییر نداشتیم اما داخل کلاس کلین کد این کار انجام شده است
</p>

2021-08-16 17:30 UTC, MahdiHma approved these changes
خدا قوت و خسته نباشید

2021-08-16 17:30 UTC, MahdiHma commented on Phase3/src/main/java/FileReader.java
> +            return "";
اینجا میتونید یه استرینگ ارور با مفهوم به کاربر نشون بدید.
ریترن کردن نال یا استرینگ خالی برای دیباگ و کاربر مفهومی نداره احتمالا

2021-08-17 06:54 UTC, merged