Phase8 ef core
Star-Academy/Summer1400-SE-Team22 pull request #8
Opened 2021-08-12 17:29 UTC by abolfazlghalandary

closes https://github.com/Star-Academy/codestar-intern-issues/issues/424

2021-08-14 09:40 UTC, nazari02105 commented on SampleLibrary/DatabaseInitializer/Program.cs
> +    }
در کل متد مین بهتر است کار خاصی انجام ندهد و تا جایی که میشود خلوت باشد
در اینجا کل کارها را مین انجام میدهد

2021-08-14 16:44 UTC, nazari02105 commented on SampleLibrary/SampleLibrary/FileReader.cs
> +        public static string ReadFileContent(string fileAddress)
بهتر هست در کل تا جایی که می توان از استاتیک استفاده نکرد چون هم خیلی برنامه رو محدود میکند و هم اگر در فاز 
ASP 
بحث شبکه وسط بیاد و در کل برای یک پروژه بهتر این استاتیک مشکل ساز می شود

2021-08-14 16:56 UTC, nazari02105 commented on SampleLibrary/SampleLibrary/FileReader.cs
> +            }
اینجا بهتر هست در اکسپشن مورد با معنا تری گذاشته شود چون این اکسپشن دلالیش مختلف دارد 
مثل نبودن فایل و یا باز بودن اون در جای دیگه یا مثلا بحث 
lock 
کردن فایل ها مثل
Advisory lock & Explicit lock
که هر کدام ارور جداگانه ای می دهند و بهتر است ارور چاپ شود و یا جوری به کسی که از این لایبرری قرار هست استفاده کند 
بفهمانید

2021-08-14 16:57 UTC, nazari02105 commented on SampleLibrary/SampleLibrary/InvertedIndex.cs
> +{
در این کلاس یکی از مهم ترین اصول 
SOLID
که همان 
Single Responsibility
هست رعایت نشده و این کلاس خیلی کارهای متنوعی را انجام میدهد که بهتر است این ها شکسته شود به کلاس های جداگانه

2021-08-14 17:00 UTC, nazari02105 commented on SampleLibrary/SampleLibrary/InvertedIndex.cs
> +            }
طبق چیزی که در کارگاه 
TDD
گفته شد این کلاس وظیفه ی این را ندارد که کلاس دیگری را 
new 
کند چون یاز همون از کیفیت کد کم میکند و تست نویسی را سخت میکند
این باید به طریقی بهش پاس داده شود و خودش نباید آن را بسازد

2021-08-14 17:02 UTC, nazari02105 commented on SampleLibrary/SampleLibrary/InvertedIndex.cs
> +            }
در کل در خیلی از جاها که ما برای همه ی آن ها کامنت نذاشتیم، میشد از 
LINQ 
استفاده کرد و بهتر است هر جایی که میشود از این قابلیت استفاده کرد، استفاده کنید
چون خیلی کد را بهتر میکند
فقط جاهایی که این عبارت شامل
LINQ 
خیلی دارد طولانی میشود به چند خط شکسته شود

2021-08-14 17:04 UTC, nazari02105 commented on SampleLibrary/SampleLibrary/SearchContext.cs
> +        }
در کل بهتر است این 
Connection String 
در کد آورده نشود مخصوصا شما که برای دیتابیستان رمز هم تعریف کردید و خوب نیست در کد آمده باشد
بهتر است از قابلیت های
App.config 
استفاده کنید

2021-08-14 17:05 UTC, nazari02105 commented on SampleLibrary/SampleLibrary/Searcher.cs
> +        }
تابع بسیار بسیار طولانی است و بهتر است شکسته شود به چند متد

2021-08-14 17:06 UTC, nazari02105 commented on SampleLibrary/SampleLibrary/WordInfo.cs
> +        }
وقتی به حالت
{ get; set; }
نوشته شده است دیگر نیازی به تعریف  گتر ندارد به نظرم

2021-08-14 17:09 UTC, nazari02105 commented on SampleLibrary/SampleLibrary.Test/SearcherTest.cs
> +        {
نامگذاری تست ها خوب نیست و بهتر است جوری باشد که حالتی که دارد چک میکند و خروجی مدنظر
به شکل خلاصه آورده شده باشد در اسم متد تست

2021-08-14 17:11 UTC, nazari02105 commented on SampleLibrary/SampleLibrary/Searcher.cs
> +            var words = new List<string>(searchingExpression.Split(' '));
در کل یکی از کارهایی که بهتر است انجام بشود این است که ورودی تابع حتی در شرایطی که 
call by value 
است تغییر داده نشود

2021-08-14 17:12 UTC, nazari02105 commented on SampleLibrary/SampleLibrary/Searcher.cs
> +    {
در این کلاس هم 
S
در 
Solid 
رعایت نشده است خیلی

2021-08-14 17:13 UTC, nazari02105 commented on SampleLibrary/SampleLibrary/Word.cs
> +
اینطور که من فهمیدم از این کانستراکتور استفاده ای نشده 
اگر واقعا استفاده ای نشده بهتر است نباشد کلا
همین اتفاق در کلاس
WordInfo
افتاده است

2021-08-14 17:14 UTC, nazari02105 commented on SampleLibrary/SampleLibrary/Searcher.cs
> +using System.Linq;
ایمپورت بدون استفاده

2021-08-14 17:16 UTC, nazari02105 commented on SampleLibrary/SampleLibrary/Searcher.cs
> +                PrintResults(Search(input));
در مورد 
statement 
این 
if 
و در کل هر جایی که 
{ }
نیاز هست به لینک زیر توجه کنید
https://stackoverflow.com/questions/2125066/is-it-a-bad-practice-to-use-an-if-statement-without-curly-braces

2021-08-14 17:18 UTC, nazari02105 requested changes
در کل بهتر است با دید 
TDD
همه فاز ها از فاز ۵ به بعد زده شود چون کیفیت کد را خیلی بالا میبرد ولی از آنجا که شما هیچ اینترفیسی نداشتید و همینطور در تست هایتان در کامیت های اولیه از قابلیت ماک کردن استفاده نکردید مشخص هست که با این دید جلو نرفته اید
این کامنت فقط پیشنهادی است که سعی کنید تا جایی که می توانید از 
TDD 
استفاده کنید

2021-08-14 18:04 UTC, mohammad258852 commented on SampleLibrary/SampleLibrary.Test/SearcherTest.cs
> +    public class SearcherTest : BeforeAfterTestAttribute
بهتر بود برای تست
Searcher
از داده‌های اصلی استفاده نمیکردید و از داده‌های کوچک‌تر با حجم کمتر و نتیجه قابل حدس استفاده میکردید

2021-08-14 18:04 UTC, mohammad258852 commented on SampleLibrary/SampleLibrary/InvertedIndex.cs
> +                HandleIndexing(fileAddress, word.ToLower(), ref position);
متغیر
position
اگر در همین حلقه تغییر میکرد بهتر بود

2021-08-16 06:22 UTC, abolfazlghalandary commented on SampleLibrary/DatabaseInitializer/Program.cs
> +    }
✔

2021-08-16 06:26 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/FileReader.cs
> +        public static string ReadFileContent(string fileAddress)
خود رایدر پیشنهاد استاتیک کردنو داد
این کلاس یه متد بیشتر نداره
و این متد هم به فیلد خاصی از آبجکت نیاز نداره که هر بر بار اینستنس ازش ساخته بشه
فکر میکنم اینطوری بهتر باشه

2021-08-16 06:32 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/FileReader.cs
> +            }
✔

2021-08-16 06:39 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/InvertedIndex.cs
> +                HandleIndexing(fileAddress, word.ToLower(), ref position);
✔

2021-08-16 07:45 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/InvertedIndex.cs
> +{
فقط وظیفه ایندکس کردن رو داره
کدوم قسمتش قابل جداشدنه یا کار نامربوط انجام میده؟

2021-08-16 08:04 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/InvertedIndex.cs
> +            }
✔

2021-08-16 08:21 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/Searcher.cs
> +        }
✔

2021-08-16 08:24 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/WordInfo.cs
> +        }
✔

2021-08-16 08:29 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary.Test/SearcherTest.cs
> +    public class SearcherTest : BeforeAfterTestAttribute
بله زمان پیاده سازی راجع به وجود "مموری دیتابیس" اطلاعی نداشتیم

2021-08-16 08:34 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/Searcher.cs
> +                PrintResults(Search(input));
✔

2021-08-16 08:35 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/Searcher.cs
> +using System.Linq;
✔

2021-08-16 08:36 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/Word.cs
> +
ای اف کور برای ساخت آبجکت زمانی که به دیتابیس کوئری میزنیم نیاز به کانستراکتور بدون فیلد داره

2021-08-16 08:39 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/Searcher.cs
> +    {
وظیفش فقط سرچ کردنه
به نظرم جدا کردن کلاساش چیز تمیزی ازش در نمیاره

2021-08-16 08:40 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/Searcher.cs
> +            var words = new List<string>(searchingExpression.Split(' '));
✔

2021-08-16 08:48 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary.Test/SearcherTest.cs
> +        {
✔

2021-08-16 10:24 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/InvertedIndex.cs
> +            }
تا حد ممکن سعی کردیم از
linq
استفاده کنیم. 
برای قسمتی که کامنت شده چطوری میشه از
linq 
استفاده کرد؟

2021-08-16 11:12 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/SearchContext.cs
> +        }
✔

2021-08-17 05:30 UTC, nazari02105 commented on SampleLibrary/SampleLibrary/InvertedIndex.cs
> +{
مثلا اون بخش های تمیز کاریش مثل حذف استاپ ورد ها و یا کوچک کردن حرف ها و یا اگر استم کردید، کار استم کردن و اینا بهتر است در کلاس جداگانه ای انجام شود

2021-08-17 05:31 UTC, nazari02105 commented on SampleLibrary/SampleLibrary/InvertedIndex.cs
> +            }
خود فورایچ را با 
linq
میتوان زد و چون این 
{ }
هارو حذف میکند در شمای کلی به نظرم خیلی تاثیر دارد

2021-08-17 05:35 UTC, nazari02105 commented on SampleLibrary/SampleLibrary/Searcher.cs
> +    {
چرا دیگه اینجا هم می توان آن بحث هندل کردن مثبت و منفی پشت کلمه ها را در یک کلاس هندل کرد
اون بخش حذف استاپ ورد ها و کوچک کردن حرف ها و استم کردنشان را هم در همان کلاسی که از قبل ساخته شده
اینگونه داپلیکیت این بخش با 
InvertedIndex 
هم از بین می رود و در کل خیلی تمیز تر میشود
آهان ورودی گرفتن از کاربر هم به نظرم کلا در کلاس جداگانه ای باشد خیلی بهتر است

2021-08-17 07:39 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/InvertedIndex.cs
> +            }
✔

2021-08-17 07:57 UTC, mohammad258852 approved these changes

2021-08-17 08:08 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/Searcher.cs
> +    {
✔

2021-08-17 08:14 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/InvertedIndex.cs
> +{
حذف استاپ وردها توی سرچر انجام میشه و در خلال فرآیند اصلی هستش(صرفا توی حلقه ایگنور میشه)
استم انجام ندادیم
کوچک کردن حرفها هم یک خط هستش کلا

2021-08-18 09:44 UTC, nazari02105 approved these changes

2021-08-21 15:16 UTC, AlirezaT99 approved these changes
خسته نباشید

2021-08-21 15:16 UTC, AlirezaT99 commented on SampleLibrary/SampleLibrary/Searcher.cs
> +                {
این فیلتر بهتر و زیباتره که قبل از حلقه نوشته بشه.. یا حتی در یه متد جدا

2021-08-21 15:16 UTC, AlirezaT99 commented on SampleLibrary/SampleLibrary/Searcher.cs
> +                }
Exists

2021-08-21 15:16 UTC, AlirezaT99 commented on SampleLibrary/SampleLibrary/Searcher.cs
> +        }
استفاده از
string formatting
اینجاها خواناتره.

2021-08-21 15:16 UTC, AlirezaT99 commented on SampleLibrary/SampleLibrary/Searcher.cs
> +            return SearchContext.WordInfos.Where(y => wordIds.Contains(y.WordId)).ToList();
اینجا و چند جای دیگه
زیباتره که فراخوانی متدها زیر هم نوشته بشن:
``` csharp
... = words
    .Where(...)
    .Select(...)
```

2021-08-21 15:16 UTC, AlirezaT99 commented on SampleLibrary/SampleLibrary/Searcher.cs
> +        }
this?

2021-08-21 15:16 UTC, AlirezaT99 commented on SampleLibrary/SampleLibrary/SearchContext.cs
> +        }
<div dir="rtl">
حتی یه فایل جیسون می‌تونه وجود داشته باشه و مسیرش به عنوان arg به main داده بشه (یا در یه مسیر دیفالت دنبالش بگرده).
و بعد از ولیدیت شدن فیلدها، توی یه متد رشته‌ی لازم ازشون ساخته شه و خروجیش بیاد اینجا.
(اینجوری بعدها توی پایپ‌لاین هم می‌شه با تنظیم یه سری فیلدها، این فایل رو تولید کرد و گذاشت کنار برنامه)
</div>

2021-08-24 11:15 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/Searcher.cs
> +                {
✔

2021-08-24 11:15 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/Searcher.cs
> +                }
✔

2021-08-24 11:18 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/Searcher.cs
> +        }
✔

2021-08-24 11:21 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/Searcher.cs
> +            return SearchContext.WordInfos.Where(y => wordIds.Contains(y.WordId)).ToList();
✔

2021-08-24 11:38 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/Searcher.cs
> +        }
✔

2021-08-24 11:46 UTC, abolfazlghalandary commented on SampleLibrary/SampleLibrary/SearchContext.cs
> +        }
✔

2021-08-27 06:44 UTC, MahdiHma approved these changes
بسیار عالی

2021-08-27 06:54 UTC, merged